import 'bootstrap';
import "./sass/build.sass";
import "./sass/fonts.sass";
import "./sass/bootstrap.sass";
import "./index.pug";
import "./login.pug";
import "./support.pug";
import "./create_account.pug";
import "./account_information.pug";
